name = "myworkweb-signup"
main = "src/index.ts"
compatibility_date = "2024-09-23"
workers_dev = true
account_id = "783a9c9379e73a460d4cc9b0d76e164f"

[build]
command = "npm install && npm run build"
cwd = "."

[vars]
SHAREPOINT_SITE_URL = "https://myworkweb.sharepoint.com/sites/myworkhome"
REDIRECT_URL = "https://myworkweb-signup.wjlee1860.workers.dev/login"
TENANT_ID = "77ad8ab8-7d87-4c2c-a442-8d26f9c8fab1"
CLIENT_ID = "dcab512e-de4e-4f08-a23d-36c1149b2cf5"
SHAREPOINT_LIST_ID = "16dc1ef7-2507-47a8-8f20-94679fbc3b39"
SHAREPOINT_SITE_ID = "myworkweb.sharepoint.com,e6b04aa7-7c22-4404-8ce1-b41f033a993d,a88a3f71-fd87-4ee5-9a7c-0ccdf4454bfe"
