name = "myworkweb-signup"
main = "src/index.ts"
compatibility_date = "2024-09-23"
workers_dev = true
account_id = "783a9c9379e73a460d4cc9b0d76e164f"

[build]
command = "npm install && npm run build"
cwd = "."

[env.development]
name = "development"
workers_dev = true

[env.development.vars]
SHAREPOINT_SITE_URL = "https://myworkweb.sharepoint.com/sites/myworkhome"
REDIRECT_URL = "http://localhost:8787/login"

[env.production]
name = "production"
route = "myworkweb-signup.wjlee1860.workers.dev/*"
workers_dev = true

[env.production.vars]
SHAREPOINT_SITE_URL = "https://myworkweb.sharepoint.com/sites/myworkhome"
REDIRECT_URL = "https://myworkweb-signup.wjlee1860.workers.dev/login"

